language: csharp
#dist: trusty
sudo: false
mono: none
dotnet:  5.0.200
script:
- dotnet restore
- dotnet build
notifications:
 email:
    recipients:
    - alvaroximenesrj@gmail.com
    - alvarocamargorj2018@gmail.com
    on_success: always
    on_failure: always